// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutJobs: typeof import('./components/AboutJobs.vue')['default']
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    AboutProject: typeof import('./components/AboutProject.vue')['default']
    AsideContent: typeof import('./components/AsideContent.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CibMysql: typeof import('~icons/cib/mysql')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    'GrommetIcons:js': typeof import('~icons/grommet-icons/js')['default']
    Icon: typeof import('~icons/ic/on')['default']
    IconAccessibility: typeof import('~icons/ic/on-accessibility')['default']
    IconAccountBox: typeof import('~icons/ic/on-account-box')['default']
    IconCarbonAccessibility: typeof import('~icons/ic/on-carbon-accessibility')['default']
    IconMdiAccount: typeof import('~icons/ic/on-mdi-account')['default']
    IconMdiAccountBox: typeof import('~icons/ic/on-mdi-account-box')['default']
    IconMdiLaravel: typeof import('~icons/ic/on-mdi-laravel')['default']
    IconsMysql: typeof import('~icons/ic/ons-mysql')['default']
    LogosWakatime: typeof import('~icons/logos/wakatime')['default']
    'Mdi:emailOutline': typeof import('~icons/mdi/email-outline')['default']
    MdiCionsJs: typeof import('~icons/mdi/cions-js')['default']
    MdiEmail: typeof import('~icons/mdi/email')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiJs: typeof import('~icons/mdi/js')['default']
    MdiLanguageTypescript: typeof import('~icons/mdi/language-typescript')['default']
    MdiLaravel: typeof import('~icons/mdi/laravel')['default']
    MdiMail: typeof import('~icons/mdi/mail')['default']
    MdiPhone: typeof import('~icons/mdi/phone')['default']
    MdiTelegram: typeof import('~icons/mdi/telegram')['default']
    MdiTypescript: typeof import('~icons/mdi/typescript')['default']
    MdiVuejs: typeof import('~icons/mdi/vuejs')['default']
    MdiWakatime: typeof import('~icons/mdi/wakatime')['default']
    README: typeof import('./components/README.md')['default']
    'SimpleIcons:wakatime': typeof import('~icons/simple-icons/wakatime')['default']
    SimpleIconsWakatime: typeof import('~icons/simple-icons/wakatime')['default']
  }
}

export { }
